version: '3'

services:
  server:
    image: tinkerpop/gremlin-server
    ports:
      - 8182:8182

  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - server

  visual:
    image: prabushitha/gremlin-visualizer
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - server
